"""
Configuration parameters for the Deep RL Pygame Arena.
All game settings, reward values, and training parameters defined here.
"""

import math

# Window dimensions
WINDOW_WIDTH = 960
WINDOW_HEIGHT = 680

# Player settings
PLAYER_RADIUS = 15
PLAYER_MAX_HEALTH = 100
PLAYER_SPEED = 4.0
PLAYER_ROTATION_SPEED = 5.0
PLAYER_FIRE_COOLDOWN = 10
PLAYER_INITIAL_POSITION = (WINDOW_WIDTH // 2, WINDOW_HEIGHT // 2)

# Enemy settings
ENEMY_RADIUS = 12
ENEMY_HEALTH = 15 
ENEMY_SPEED = 1.2
ENEMY_DAMAGE = 5
ENEMY_COLLISION_DAMAGE = 10

# Spawner settings
SPAWNER_RADIUS = 25
SPAWNER_HEALTH = 40  
SPAWNER_SPAWN_INTERVAL = 150  
SPAWNER_MAX_ENEMIES = 3  

# Projectile settings
PROJECTILE_RADIUS = 4
PROJECTILE_SPEED = 12.0
PROJECTILE_DAMAGE = 15
PROJECTILE_LIFETIME = 60 

# Phase settings
INITIAL_SPAWNER_COUNT = 1
SPAWNERS_PER_PHASE_INCREMENT = 1
MAX_PHASE = 3

# Episode settings
MAX_EPISODE_STEPS = 1500
FRAMES_PER_SECOND = 60

# Reward values
REWARD_ENEMY_KILL = 5.0  
REWARD_SPAWNER_KILL = 100.0
REWARD_PHASE_COMPLETE = 150.0
REWARD_DAMAGE_TAKEN = -3.0
REWARD_DEATH = -50.0
REWARD_TIME_PENALTY = 0.0

# Observation normalization bounds
POSITION_MAX = max(WINDOW_WIDTH, WINDOW_HEIGHT)
VELOCITY_MAX = max(PLAYER_SPEED, ENEMY_SPEED) * 2
DISTANCE_MAX = math.sqrt(WINDOW_WIDTH ** 2 + WINDOW_HEIGHT ** 2)

# Color definitions (RGB format)
COLOR_BACKGROUND = (20, 20, 30)
COLOR_PLAYER = (100, 200, 255)
COLOR_PLAYER_DAMAGED = (255, 100, 100)
COLOR_ENEMY = (255, 80, 80)
COLOR_SPAWNER = (180, 80, 180)
COLOR_SPAWNER_ACTIVE = (220, 100, 220)
COLOR_PROJECTILE_PLAYER = (255, 255, 100)
COLOR_PROJECTILE_ENEMY = (255, 150, 50)
COLOR_HEALTH_BAR = (100, 255, 100)
COLOR_HEALTH_BAR_BG = (60, 60, 60)
COLOR_TEXT = (200, 200, 200)

# Training hyperparameters
TRAINING_TIMESTEPS = 300000
LEARNING_RATE = 0.0003
NETWORK_ARCHITECTURE = [128, 128]
